server:
  port: 8080

spring:
  mail:
    host: smtp.gmail.com
    username: ${USER_MAIL}
    password: ${USER_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

